#!/system/bin/sh
# Battery drain script by aris setiawan, for saving battery your ROM

# Stone cold kernel
echo "0" > /proc/sys/kernel/panic_on_oops;
echo "0" > /proc/sys/kernel/panic;

# Battery tuner

    echo "1000" > /proc/sys/vm/dirty_expire_centisecs
    echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
    echo "1536,2048,14567,15360,29500,32500" > /sys/module/lowmemorykiller/parameters/minfree;
    echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
    echo 95 > /sys/devices/system/cpu/cpufreq/conservative/up_threshold;
    echo 1500000 > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate;
    echo 30 > /sys/devices/system/cpu/cpufreq/conservative/down_differential;
    echo 1 > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
		sysctl -w vm.dirty_expire_centisecs=1000;
		sysctl -w vm.dirty_writeback_centisecs=5000;
		echo 0 > /proc/sys/vm/swappiness;
		sysctl -w vm.min_free_kbytes=4096;
		setprop pm.sleep_mode 1
		setprop ro.ril.disable.power.collapse 1
		sysctl -w vm.oom_kill_allocating_task=1;
		setprop ro.mot.eri.losalert.delay 1000
		echo "noop" > /sys/block/mmcblk0/queue/scheduler;
		echo 0 > /proc/sys/vm/swappiness;
    echo 1 > /proc/sys/vm/oom_dump_tasks;
    echo 90 > /proc/sys/vm/dirty_ratio;
    echo 85 > /proc/sys/vm/dirty_background_ratio;
    echo 15 > /proc/sys/vm/vfs_cache_pressure;

# Disable I/O Stats
if [ -e /queue/iostats ]; then
echo 0 > /queue/iostats;
fi;  

# Cache cleaner

REMOVE_CACHE=1

if busybox [ $REMOVE_CACHE -eq 1 ]; then
	CACHE_DIR=(` busybox find /data/data -type d -iname *cache* -print `);
	for dir in ${CACHE_DIR[*]}; do
		busybox find $dir -type f -delete
	done
	log -p i -t boot "Cleared data cache..."
fi